Hide Dropdown When Search Input is Empty
ember-learn/ember-learn-search-components pull request #10
Opened 2018-05-18 05:38 UTC by nummi

Addresses: https://github.com/ember-learn/guides-app/issues/65

2018-05-24 11:19 UTC, sivakumar-kailasam requested changes

2018-05-24 11:19 UTC, sivakumar-kailasam commented on addon/components/search-input.js
> +    return get(this, '_focused') && !!get(this, 'value').length;
`isPresent` might be more verbose here.

2018-05-24 19:45 UTC, nummi commented on addon/components/search-input.js
> +    return get(this, '_focused') && !!get(this, 'value').length;
Like this?

``` javascript
_dropdownVisible: computed('_focused', 'value', function() {
  return get(this, '_focused') && isPresent(get(this, 'value'));
})
```

2018-05-24 19:46 UTC, sivakumar-kailasam commented on addon/components/search-input.js
> +    return get(this, '_focused') && !!get(this, 'value').length;
Yes

2018-05-28 22:54 UTC, nummi commented on addon/components/search-input.js
> +    return get(this, '_focused') && !!get(this, 'value').length;
Change made.

2018-05-28 23:54 UTC, sivakumar-kailasam approved these changes
Thanks @nummi

2018-05-28 23:54 UTC, merged